version: '3.1'
services:
  test-web-app:
    image: test-web-app
    build:
     context: .
     dockerfile: TestWebApp/Dockerfile
    ports:
     - "7000:7000"
  nginx:
    image: nginx:latest
    depends_on:
      - test-web-app
    ports:
      - 80:80
    volumes:
       - ./nginx:/etc/nginx:ro
    links:
       - test-web-app
