version: '3.1'
services:
  TestWebApp:
    build: ./TestWebApp
    ports:
     - "7000:7000"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
